#!/usr/bin/env bash
# Quick usage:
#   bash ./script/function_localization.sh
#     - Default mode: run function-level localization from existing
#       results/*.minimax-m2.7 folders via localization2.1_withoutEmbedding.sh
#
#   bash ./script/function_localization.sh --all
#     - Default mode: run all detected m2.7 result folders
#
#   bash ./script/function_localization.sh --legacy
#     - Legacy mode: select datasets from data/<lang>/*.jsonl and run
#       localization1.4.sh + localization2.1.sh
#
#   bash ./script/function_localization.sh -h
#     - Show full help

set -euo pipefail
if [[ "${DEBUG:-0}" == "1" ]]; then
  set -x
fi

# Optional API env bootstrap (same style as run.sh)
if [[ -f script/api_key.sh ]]; then
  # shellcheck disable=SC1091
  source script/api_key.sh
else
  echo "[WARN] script/api_key.sh not found. Please export API env vars manually."
fi

export PYTHONPATH="${PYTHONPATH:-}:$(pwd)"

print_usage() {
  cat <<'EOF_USAGE'
Usage:
  bash ./script/function_localization.sh [--all] [--legacy] [-h|--help]

Modes:
  default mode        Run function-level localization from existing m2.7 results
                      (calls script/localization2.1_withoutEmbedding.sh)
  --legacy            Run previous data-driven flow
                      (calls script/localization1.4.sh + script/localization2.1.sh)

Options:
  --all               In default mode, run all detected m2.7 folders directly
  --legacy            Enable old behavior based on data/<lang>/*.jsonl selection
  -h, --help          Show this help message

Environment overrides (default mode):
  RESULTS_DIR         Root directory containing result folders (default: results)
  NJ                  Number of threads (default: 2)
  DATASET             Dataset mode passed through (default: local_json)
  SPLIT               Split passed through (default: test)

Environment overrides (legacy mode):
  SWEBENCH_LANG       cpp/javascript/typescript (default: cpp)
  PROJECT_FILE_LOC    default: structure
  DATASET             default: local_json
  SPLIT               default: test
  NJ                  default: 2
  NUM_SETS            default: 2
  FOLDER_NAME         optional fixed output folder; if unset auto-generated by project+model
EOF_USAGE
}

MODE="results"
RUN_ALL=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --all)
      RUN_ALL=1
      shift
      ;;
    --legacy)
      MODE="legacy"
      shift
      ;;
    -h|--help)
      print_usage
      exit 0
      ;;
    *)
      echo "[ERROR] Unknown argument: $1"
      print_usage
      exit 1
      ;;
  esac
done

sanitize_name() {
  printf "%s" "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9._-]+/-/g; s/^-+//; s/-+$//'
}

count_instance_ids() {
  local project_file="$1"
  local count=0
  if command -v rg >/dev/null 2>&1; then
    count="$(
      rg -o '"instance_id"\s*:\s*"[^"]+"' "${project_file}" \
        | sed -E 's/.*"instance_id"\s*:\s*"([^"]+)"/\1/' \
        | awk '!seen[$0]++' \
        | wc -l \
        | tr -d ' '
    )"
  else
    count="$(
      grep -oE '"instance_id"[[:space:]]*:[[:space:]]*"[^"]+"' "${project_file}" \
        | sed -E 's/.*"instance_id"[[:space:]]*:[[:space:]]*"([^"]+)"/\1/' \
        | awk '!seen[$0]++' \
        | wc -l \
        | tr -d ' '
    )"
  fi

  if [[ "${count}" == "0" ]]; then
    echo "[ERROR] No instance_id found in ${project_file}."
    return 1
  fi
  PROJECT_INSTANCE_COUNT="${count}"
}

run_results_mode() {
  export NJ="${NJ:-2}"
  export DATASET="${DATASET:-local_json}"
  export FOLDER_NAME="${FOLDER_NAME:-}"
  export SWEBENCH_LANG="${SWEBENCH_LANG:-cpp}"
  export PROJECT_FILE_LOC="${PROJECT_FILE_LOC:-structure}"
  export DATASET="${DATASET:-local_json}"
  export SPLIT="${SPLIT:-test}"
  export FILTER_TOP_N=500
  local results_dir
  results_dir="${RESULTS_DIR:-results}"
  if [[ "${SWEBENCH_LANG}" == "javascript" ]]; then
    DATA_LANG_DIR="js"
  elif [[ "${SWEBENCH_LANG}" == "typescript" ]]; then
    DATA_LANG_DIR="ts"
  else
    DATA_LANG_DIR="${SWEBENCH_LANG}"
  fi
  DATA_DIR="data/${DATA_LANG_DIR}"

  if [[ ! -d "${results_dir}" ]]; then
    echo "[ERROR] Results directory not found: ${results_dir}"
    exit 1
  fi

  collect_projects_results() {
    PROJECT_DIRS=()
    while IFS= read -r one_dir; do
      PROJECT_DIRS+=("${one_dir}")
    done < <(
      find "${results_dir}" -mindepth 1 -maxdepth 1 -type d \
        -name "*.minimax-m2.7" \
        | sort
    )

    if [[ ${#PROJECT_DIRS[@]} -eq 0 ]]; then
      echo "[ERROR] No m2.7 result folders found under ${results_dir}."
      echo "[HINT] Expected folder names like: <project>_dataset.minimax-m2.7"
      exit 1
    fi
  }

  list_projects_results() {
    echo ""
    echo "Available m2.7 result folders in ${results_dir}:"
    local i
    for i in "${!PROJECT_DIRS[@]}"; do
      printf "%3d) %s\n" "$((i + 1))" "$(basename "${PROJECT_DIRS[$i]}")"
    done
    echo ""
  }

  run_one_project_results() {
    local project_dir="$1"
    local project_name
    local start_file
    local project_key
    local matched_dataset
    local backup_dir

    project_name="$(basename "${project_dir}")"
    start_file="${project_dir}/file_level/loc_outputs.jsonl"
    project_key="$(basename "${project_dir}" .minimax-m2.7)"

    if [[ ! -f "${start_file}" ]]; then
      echo "[WARN] Skip ${project_name}: missing ${start_file}"
      return 0
    fi

    export FOLDER_NAME="${project_name}"
    unset TARGET_ID

    matched_dataset=""
    if [[ "${DATASET}" == "local_json" ]]; then
      if [[ ! -d "${DATA_DIR}" ]]; then
        echo "[ERROR] Data directory not found: ${DATA_DIR}"
        return 1
      fi

      while IFS= read -r one_file; do
        if [[ "$(basename "${one_file}" .jsonl | tr '[:upper:]' '[:lower:]')" == "$(printf "%s" "${project_key}" | tr '[:upper:]' '[:lower:]')" ]]; then
          matched_dataset="${one_file}"
          break
        fi
      done < <(find "${DATA_DIR}" -maxdepth 1 -name "*.jsonl" | sort)

      if [[ -z "${matched_dataset}" ]]; then
        echo "[ERROR] No matching dataset jsonl for ${project_name} under ${DATA_DIR}"
        echo "[HINT] Expected a file like ${project_key}.jsonl"
        return 1
      fi
    fi

    echo "[INFO] Running function-level localization (without embedding) for ${project_name}"
    if [[ "${DATASET}" == "local_json" ]]; then
      backup_dir="$(mktemp -d "${TMPDIR:-/tmp}/magentless_results_${DATA_LANG_DIR}_XXXXXX")"
      (
        cleanup() {
          set +e
          while IFS= read -r one_file; do
            mv "${one_file}" "${DATA_DIR}/"
          done < <(find "${backup_dir}" -maxdepth 1 -name "*.jsonl" | sort)
          rmdir "${backup_dir}" >/dev/null 2>&1 || true
        }
        trap cleanup EXIT

        while IFS= read -r one_file; do
          if [[ "${one_file}" != "${matched_dataset}" ]]; then
            mv "${one_file}" "${backup_dir}/"
          fi
        done < <(find "${DATA_DIR}" -maxdepth 1 -name "*.jsonl" | sort)

        ./script/localization2.1_withoutEmbedding.sh
      )
    else
      ./script/localization2.1_withoutEmbedding.sh
    fi
    echo "[INFO] Finished ${project_name}. Output: results/${project_name}/related_elements/"
  }

  collect_projects_results

  if (( RUN_ALL == 1 )); then
    echo "[INFO] --all enabled. Running ${#PROJECT_DIRS[@]} project(s)."
    for one_project in "${PROJECT_DIRS[@]}"; do
      run_one_project_results "${one_project}"
    done
    echo "[INFO] Batch run completed."
    return 0
  fi

  while true; do
    collect_projects_results
    list_projects_results

    read -r -p "Select one project to run (number, a=all, or q to quit): " PICK
    if [[ "${PICK}" == "q" || "${PICK}" == "Q" ]]; then
      echo "Exit without running more projects."
      break
    fi

    if [[ "${PICK}" == "a" || "${PICK}" == "A" ]]; then
      read -r -p "Run ALL listed projects now? [y/N]: " CONFIRM_ALL
      if [[ "${CONFIRM_ALL}" == "y" || "${CONFIRM_ALL}" == "Y" ]]; then
        for one_project in "${PROJECT_DIRS[@]}"; do
          run_one_project_results "${one_project}"
        done
        echo "[INFO] All listed projects finished."
        break
      fi
      continue
    fi

    if ! [[ "${PICK}" =~ ^[0-9]+$ ]]; then
      echo "[WARN] Invalid input: ${PICK}. Please input a number, a, or q."
      continue
    fi

    IDX=$((PICK - 1))
    if (( IDX < 0 || IDX >= ${#PROJECT_DIRS[@]} )); then
      echo "[WARN] Out of range: ${PICK}."
      continue
    fi

    SELECTED_DIR="${PROJECT_DIRS[$IDX]}"
    SELECTED_NAME="$(basename "${SELECTED_DIR}")"

    echo "[INFO] Selected project folder: ${SELECTED_NAME}"
    read -r -p "Run this project now? [y/N]: " CONFIRM
    if [[ "${CONFIRM}" != "y" && "${CONFIRM}" != "Y" ]]; then
      echo "[INFO] Skip ${SELECTED_NAME}."
      continue
    fi

    run_one_project_results "${SELECTED_DIR}"

    read -r -p "Continue and select another project? [y/N]: " CONTINUE_PICK
    if [[ "${CONTINUE_PICK}" != "y" && "${CONTINUE_PICK}" != "Y" ]]; then
      break
    fi
  done
}

run_legacy_mode() {
  export NJ="${NJ:-2}"
  export NUM_SETS="${NUM_SETS:-2}"
  USER_DEFINED_FOLDER_NAME=0
  if [[ -n "${FOLDER_NAME:-}" ]]; then
    USER_DEFINED_FOLDER_NAME=1
  fi
  export FOLDER_NAME="${FOLDER_NAME:-}"
  export SWEBENCH_LANG="${SWEBENCH_LANG:-cpp}"
  export PROJECT_FILE_LOC="${PROJECT_FILE_LOC:-structure}"
  export DATASET="${DATASET:-local_json}"
  export SPLIT="${SPLIT:-test}"
  export FILTER_TOP_N=500

  if [[ "${DATASET}" != "local_json" ]]; then
    echo "[ERROR] Legacy mode currently supports DATASET=local_json only."
    exit 1
  fi

  if [[ "${SWEBENCH_LANG}" == "javascript" ]]; then
    DATA_LANG_DIR="js"
  elif [[ "${SWEBENCH_LANG}" == "typescript" ]]; then
    DATA_LANG_DIR="ts"
  else
    DATA_LANG_DIR="${SWEBENCH_LANG}"
  fi

  DATA_DIR="data/${DATA_LANG_DIR}"

  if ! find "${DATA_DIR}" -maxdepth 1 -name "*.jsonl" | grep -q .; then
    echo "[ERROR] No jsonl files found in ${DATA_DIR}. Please prepare dataset files first."
    exit 1
  fi

  build_folder_name_legacy() {
    local project_file="$1"
    local project_name
    local model_name
    project_name="$(basename "${project_file}" .jsonl)"
    model_name="${OPENAI_MODEL:-unknown-model}"
    project_name="$(sanitize_name "${project_name}")"
    model_name="$(sanitize_name "${model_name}")"

    if [[ -z "${project_name}" ]]; then
      project_name="project"
    fi
    if [[ -z "${model_name}" ]]; then
      model_name="model"
    fi

    printf "%s.%s" "${project_name}" "${model_name}"
  }

  run_selected_project_batch_legacy() {
    local selected_file="$1"
    local selected_name
    selected_name="$(basename "${selected_file}")"
    local backup_dir
    backup_dir="$(mktemp -d "${TMPDIR:-/tmp}/magentless_${DATA_LANG_DIR}_XXXXXX")"

    (
      cleanup() {
        set +e
        while IFS= read -r one_file; do
          mv "${one_file}" "${DATA_DIR}/"
        done < <(find "${backup_dir}" -maxdepth 1 -name "*.jsonl" | sort)
        rmdir "${backup_dir}" >/dev/null 2>&1 || true
      }
      trap cleanup EXIT

      while IFS= read -r one_file; do
        if [[ "${one_file}" != "${selected_file}" ]]; then
          mv "${one_file}" "${backup_dir}/"
        fi
      done < <(find "${DATA_DIR}" -maxdepth 1 -name "*.jsonl" | sort)

      unset TARGET_ID
      echo "[INFO] Running legacy function localization pipeline for project ${selected_name}"
      ./script/localization1.4.sh
      ./script/localization2.1.sh
    )
  }

  list_projects_legacy() {
    PROJECT_FILES=()
    while IFS= read -r one_file; do
      PROJECT_FILES+=("${one_file}")
    done < <(find "${DATA_DIR}" -maxdepth 1 -name "*.jsonl" | sort)

    if [[ ${#PROJECT_FILES[@]} -eq 0 ]]; then
      echo "[ERROR] No project files detected in ${DATA_DIR}."
      exit 1
    fi

    echo ""
    echo "Available projects in ${DATA_DIR}:"
    local i
    for i in "${!PROJECT_FILES[@]}"; do
      printf "%3d) %s\n" "$((i + 1))" "$(basename "${PROJECT_FILES[$i]}")"
    done
    echo ""
  }

  while true; do
    list_projects_legacy

    read -r -p "Select one project to run (number, or q to quit): " PICK
    if [[ "${PICK}" == "q" || "${PICK}" == "Q" ]]; then
      echo "Exit without running more projects."
      break
    fi

    if ! [[ "${PICK}" =~ ^[0-9]+$ ]]; then
      echo "[WARN] Invalid input: ${PICK}. Please input a number."
      continue
    fi

    IDX=$((PICK - 1))
    if (( IDX < 0 || IDX >= ${#PROJECT_FILES[@]} )); then
      echo "[WARN] Out of range: ${PICK}."
      continue
    fi

    SELECTED_FILE="${PROJECT_FILES[$IDX]}"
    SELECTED_NAME="$(basename "${SELECTED_FILE}")"

    if (( USER_DEFINED_FOLDER_NAME == 0 )); then
      export FOLDER_NAME
      FOLDER_NAME="$(build_folder_name_legacy "${SELECTED_FILE}")"
    fi

    count_instance_ids "${SELECTED_FILE}"

    echo "[INFO] Selected project file: ${SELECTED_NAME}"
    echo "[INFO] Total instances to run: ${PROJECT_INSTANCE_COUNT}"

    read -r -p "Run this project now? [y/N]: " CONFIRM
    if [[ "${CONFIRM}" != "y" && "${CONFIRM}" != "Y" ]]; then
      echo "[INFO] Skip ${SELECTED_NAME}."
      continue
    fi

    run_selected_project_batch_legacy "${SELECTED_FILE}"

    echo "[INFO] Project ${SELECTED_NAME} finished."
    echo "[INFO] Results are under results/${FOLDER_NAME}/"

    read -r -p "Continue and select another project? [y/N]: " CONTINUE_PICK
    if [[ "${CONTINUE_PICK}" != "y" && "${CONTINUE_PICK}" != "Y" ]]; then
      break
    fi
  done
}

if [[ "${MODE}" == "legacy" ]]; then
  run_legacy_mode
else
  run_results_mode
fi
